variables:
  TZ: Asia/Shanghai
  DEBIAN_FRONTEND: noninteractive
  MYSQL_DATABASE: jbonline_test
  MYSQL_ROOT_PASSWORD: jbonline_test_password

image: php:7.3-cli

services:
  - mariadb:latest

before_script:
  - echo "Installing deps..."
  - apt-get update -yqq
  - apt-get install build-essential curl git icu-devtools libicu-dev unzip -yqq

  - echo "Install PHP extensions..."
  - docker-php-ext-install bcmath intl pdo pdo_mysql

  - echo "Installing composer..."
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer --version

  - cp .env.gitlab .env
  - chmod 777 -R storage
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan storage:link

stages:
  - phpunit

phpunit_job:
  stage: phpunit
  script:
    - vendor/bin/phpunit
