os:
  - linux

language: php

php:
  - 7.2

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS jbonline_test;'

before_script:
  - cp .env.travis .env
  - chmod 777 -R storage
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan storage:link

script:
  - vendor/bin/phpunit
